version: '3.9'

services:

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloakPwd
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_PASSWORD: P@ssw0rd1
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mysql

  keycloak:
    image: mykeycloak
    ports:
      - 3000:8443
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: P@ssw0rd1
      # KC_DB: mysql
      # KC_DB_URL_HOST: mysql
      # KC_DB_URL_PORT: 3306
      # KC_DB_URL_DATABASE: keycloak
      # KC_DB_USERNAME: keycloak
      # KC_DB_PASSWORD: keycloakPwd
      # KC_DB_SCHEMA: keycloak
    command: start --optimized --hostname-port=3000
    depends_on:
      - mysql
    networks:
      - mysql

networks:
  mysql:

volumes:
  mysql: